apiVersion: v1
kind: Service
metadata:
  name: weather-app-loadbalancer
spec:
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3456
  type: LoadBalancer
